version: '3.7' # 파일 규격 버전

services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  nginx:
    image: nginx:latest
    user: root
    container_name: docker-compose exec service_name sh
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./var/www:/var/www
      - ./etc/letsencrypt/live:/etc/letsencrypt/live
    restart: 'always'
  app:
    image: chaewonkong/apil:latest ## 추가됨
    container_name: apil-backoffice-backend
    expose:
      - '3000'
    volumes:
      - ./.env:/app/.env

  # certbot:
  #   depends_on:
  #     - nginx
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/etc:/etc/letsencrypt
  #     - ./certbot/var:/var/lib/letsencrypt
  #     - ./www:/var/www/html
  # command: certonly --webroot --webroot-path=/var/www/html --email chaewonkong@gmail.com --agree-tos --no-eff-email --force-renewal -d office-api.apil.or.kr
